### ISSUE TITLE
No Audio or Comment option

### ISSUE THREAD

**Issue by lethaboJr21** [malefane1/ExampleRepo#3]
Please change your settings for us from your side

**Comment by malefane1** [comment]
I will for tomorrow




Malefane Matsela

Lecture - Information Technology

Information and Communication Technology Department


 O: +27 (0)16 950 9841  | ***@***.***

[cid:b20e8e7c-2d17-4d9e-a585-ede1328b0372] Andries Potgieter Blvd, Vanderbijlpark, 1900  |  Private Bag X021, Vanderbijlpark, 1911, South Africa

[cid:56233149-9ae4-4c24-8a35-97f718e3093e]

[cid:ec9ca963-b24f-4986-a1a2-983947f72ecb]



[cid:a191b420-770e-4e4e-b852-6243cdf8001d]



[cid:f182072f-c5f9-4ee9-8ba8-146fb43e340f]




[cid:8037e308-4def-41e7-861f-0ec7e18b00c9]




[cid:8c036a31-d197-4a1b-9d29-404edf3a064b]




[cid:2ada7eb7-1f22-4e04-8038-474f393609b5]

























________________________________
From: lethaboJr21 ***@***.***>
Sent: Thursday, August 1, 2024 10:25 AM
To: malefane1/ExampleRepo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [malefane1/ExampleRepo] No Audio or Comment option (Issue #3)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
________________________________
Important notice: This email is from an external source!
Exercise caution, particularly before opening attachments and/or links. If you have any uncertainty about the sender, log a call with Service Desk.
________________________________

Please change your settings for us from your side
